# Generated by Django 5.2 on 2025-05-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_project_decsription_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decsription',
            new_name='description',
        ),
    ]
