# Generated by Django 5.2 on 2025-05-08 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_rename_decsription_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pub_date'], 'verbose_name': '프로젝트', 'verbose_name_plural': '프로젝트 목록'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='grading.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='별점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='평가 일시')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='grading.project')),
            ],
            options={
                'verbose_name': '평가',
                'verbose_name_plural': '평가 목록',
            },
        ),
        migrations.DeleteModel(
            name='Raiting',
        ),
    ]
