# Generated by Django 5.2 on 2025-05-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_project_options_alter_choice_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='평균 평점'),
        ),
    ]
