# Generated by Django 5.2 on 2025-05-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_project_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avg_rating',
        ),
    ]
