# Generated by Django 5.2 on 2025-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_remove_project_avg_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '선택지', 'verbose_name_plural': '선택지 목록'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='counts',
        ),
        migrations.AddField(
            model_name='project',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='평균 평점'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='선택지 텍스트'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=models.CharField(max_length=200, verbose_name='프로젝트명'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
